# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Making sure there is a running SSH agent
# https://wiki.archlinux.org/index.php/SSH_keys#ssh-agent
if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent >! ~/.ssh-agent-thing
fi
if [[ "$SSH_AGENT_PID" == "" ]]; then
    eval "$(<~/.ssh-agent-thing)"
fi
ssh-add -l >/dev/null || alias ssh='ssh-add -l >/dev/null || ssh-add && unalias ssh; ssh'

# Working around missing icons in eg dolphin
# https://bugs.archlinux.org/task/46093
XDG_CURRENT_DESKTOP=KDE

export PATH="/home/marcus/bin:$PATH"

export EDITOR="/usr/bin/emacs"
export VISUAL="/usr/bin/emacs"

# Add ruby gems to path, if available
if which ruby >/dev/null && which gem >/dev/null; then
    PATH="$(ruby -e 'puts Gem.user_dir')/bin:$PATH"
    # Some ruby stuff likes a meaningfull ruby folder
    export GEM_HOME=$(ruby -e 'puts Gem.user_dir')
fi

# Ruby gem configuration
export GEM_HOME=$(ruby -e 'puts Gem.user_dir')
export PATH="$(ruby -e 'puts Gem.user_dir')/bin:$PATH"

if [[ `hostname` = "marcus-pc" ]]; then
   # (Currently) nothing special about this machine
fi

if [[ `hostname` = "mri-tp" ]]; then
   alias activateProxy=source\ ~/bin/activateProxy.zsh
fi

# http://www.zsh.org/mla/users/2005/msg00599.html
# Execute commands if the first parameter to the
# zsh instance is "eval"
if [[ $1 == eval ]]
then
    SOURCE_FILE=`mktemp`
    echo "$@" >! "$SOURCE_FILE"
    source "$SOURCE_FILE"
    set --
fi

# Theme configuration
autoload -Uz promptinit
promptinit
prompt sorin