#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Making sure there is a running SSH agent
# https://wiki.archlinux.org/index.php/SSH_keys#ssh-agent
if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent >! ~/.ssh-agent-thing
fi
if [[ "$SSH_AGENT_PID" == "" ]]; then
    eval "$(<~/.ssh-agent-thing)"
fi
ssh-add -l >/dev/null || alias ssh='ssh-add -l >/dev/null || ssh-add && unalias ssh; ssh'

# Working around missing icons in eg dolphin
# https://bugs.archlinux.org/task/46093
# XDG_CURRENT_DESKTOP=KDE 

export PATH="/home/marcus/bin:$PATH"

export EDITOR="/usr/bin/emacs"

# Add ruby gems to path, if available
if which ruby >/dev/null && which gem >/dev/null; then
    PATH="$(ruby -rubygems -e 'puts Gem.user_dir')/bin:$PATH"
fi

if [[ `hostname` = "marcus-pc" ]]; then
    export GOPATH=~/go
    export PATH=$PATH:~/go/bin

    export OOO_FORCE_DESKTOP=kde4
fi

if [[ `hostname` = "mri-tp" ]]; then
   alias activateProxy=source\ ~/bin/activateProxy.zsh
   export PATH=~/go:~/.cabal/bin:$PATH

   export GEM_HOME=$(ruby -e 'puts Gem.user_dir')
   export GOPATH=$HOME/go

fi
